version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Check Linting
          command: npm run lint
      - run:
          name: Running tests
          command: npm run test:coverage
